- hosts: personal-website

  tasks:
    - name: Clean up
      file:
        path: twitter_bot
        state: absent
      become: yes
      become_user: ussamaazam

    - git:
        repo: https://github.com/NuclearOreo/TwitterBot.git
        dest: twitter_bot
        version: production

    - name: NPM Install
      command: bash -c "cd twitter_bot && npm i"

    - name: Move Enviroment Variables and DockerFiles
      command: bash -c "cp botInfo/.env botInfo/Dockerfile botInfo/docker-compose.yaml  twitter_bot/"

    - name: Removing any Container
      command: bash -c "cd twitter_bot && docker-compose down -v"

    - name: Build Images
      command: bash -c "cd twitter_bot && docker-compose build"
