version: "3.1"
services:
  mongodb:
    image: mongo:3.2.6
    ports:
      - "27017:27017"

  mongo-seed:
    image: mongo:3.2.6
    links:
      - mongodb
    volumes:
      - ./quotes:/quotes
    command: 'bash -c "mongoimport --host mongodb --db bot --type json --file /quotes/Quotes.json --jsonArray"'

  bot:
    container_name: bot
    build:
      context: .
      args:
        - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
        - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
        - TWITTER_TOKEN_KEY=${TWITTER_TOKEN_KEY}
        - TWITTER_TOKEN_SECRET=${TWITTER_TOKEN_SECRET}
    command: npm run start
