FROM node:alpine

# Setting up work directory
WORKDIR /app
ADD . .

# Add arguments
ARG TWITTER_CONSUMER_KEY
ARG TWITTER_CONSUMER_SECRET
ARG TWITTER_TOKEN_KEY
ARG TWITTER_TOKEN_SECRET

# Set enviroment variables
ENV TWITTER_CONSUMER_KEY $TWITTER_CONSUMER_KEY
ENV TWITTER_CONSUMER_SECRET $TWITTER_CONSUMER_SECRET
ENV TWITTER_TOKEN_KEY $TWITTER_TOKEN_KEY
ENV TWITTER_TOKEN_SECRET $TWITTER_TOKEN_SECRET
ENV NODE_ENV 'production'

# Setup typescipt and build project
RUN npm install -g typescript
RUN npm i
RUN tsc