version: "3.1"
services:
  # database:
  #   container_name: mongodb
  #   build: quotes/.
  #   image: quotesdb
  #   command: mongod
  #   ports:
  #     - "27017:27017"
  bot:
    container_name: bot
    build:
      context: .
      args:
        - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
        - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
        - TWITTER_TOKEN_KEY=${TWITTER_TOKEN_KEY}
        - TWITTER_TOKEN_SECRET=${TWITTER_TOKEN_SECRET}
    command: npm run start
