version: "2"
services:
  database:
    container_name: mongodb
    build: quotes/.
    image: quotesdb
    command: mongod
    ports:
      - "27017:27017"
  bot:
    container_name: bot
    build: .
    image: twitterbot
    command: npm run start
